# Generated by Django 5.2.3 on 2025-07-14 17:51

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('banner', models.ImageField(upload_to='course_banners/')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price in your default currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20)),
                ('type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], db_index=True, default='free', max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(default=0, help_text='Approximate total duration in hours')),
                ('syllabus', models.TextField(blank=True, help_text='Course syllabus or outline', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback or reviews from students', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='course.category')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['type'], name='course_cour_type_959ece_idx'), models.Index(fields=['level'], name='course_cour_level_9054a3_idx'), models.Index(fields=['category', 'is_active'], name='course_cour_categor_6d7f1d_idx')],
                'unique_together': {('title', 'instructor')},
            },
        ),
    ]
