from django.db import models

# Create your models here.
class Course(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    lessson_count = models.PositiveIntegerField(default=0)
    lessons = models.ManyToManyField('Lesson', related_name='courses', blank=True)
    enrollment_count = models.PositiveIntegerField(default=0)
    enrollment_limit = models.PositiveIntegerField(default=0)
    enrolled_users = models.ManyToManyField('auth.User', related_name='enrolled_courses', blank=True)
    is_active = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    thumbnail = models.ImageField(upload_to='course_thumbnails/', blank=True, null=True)
    slug = models.SlugField(unique=True, max_length=200)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='courses', blank=True, null=True)
    prerequisites = models.ManyToManyField('self', related_name='prerequisite_courses', blank=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='courses', blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    is_published = models.BooleanField(default=False)
    is_archived = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    tags = models.ManyToManyField('Tag', related_name='courses', blank=True)
    rating = models.DecimalField(max_digits=3, decimal_places=2, default=0.00)
    average_rating = models.DecimalField(max_digits=3, decimal_places=2, default=0.00)
    total_reviews = models.PositiveIntegerField(default=0)
    language = models.CharField(max_length=50, default='English')
    video_url = models.URLField(blank=True, null=True)
    prerequisites_met = models.BooleanField(default=False)
    is_certified = models.BooleanField(default=False)
    is_free = models.BooleanField(default=False)
    is_live = models.BooleanField(default=False)
    is_on_demand = models.BooleanField(default=False)
    is_self_paced = models.BooleanField(default=False)
    is_group_course = models.BooleanField(default=False)
    is_cohort_based = models.BooleanField(default=False)
    is_mentored = models.BooleanField(default=False)
    is_project_based = models.BooleanField(default=False)
    is_exclusive = models.BooleanField(default=False)
    is_open_for_enrollment = models.BooleanField(default=True)
    is_waitlist_enabled = models.BooleanField(default=False)
    is_discounted = models.BooleanField(default=False)
    discount_percentage = models.PositiveIntegerField(default=0)
    discount_start_date = models.DateField(blank=True, null=True)
    discount_end_date = models.DateField(blank=True, null=True)
    is_certificate_issued = models.BooleanField(default=False)
    certificate_template = models.ForeignKey('CertificateTemplate', on_delete=models.SET_NULL, related_name='courses', blank=True, null=True)
    is_approved = models.BooleanField(default=False)
    is_recommended = models.BooleanField(default=False)
    is_archived_for_user = models.BooleanField(default=False)
    is_featured_for_user = models.BooleanField(default=False)
    is_visible_to_public = models.BooleanField(default=True)
    is_visible_to_enrolled_users = models.BooleanField(default=True)
    is_visible_to_instructors = models.BooleanField(default=True)
    is_visible_to_admins = models.BooleanField(default=True)
    is_visible_to_guests = models.BooleanField(default=True)
    is_visible_to_waitlisted_users = models.BooleanField(default=True)
    is_visible_to_non_enrolled_users = models.BooleanField(default=True)
    is_visible_to_premium_users = models.BooleanField(default=False)
    is_visible_to_free_users = models.BooleanField(default=True)
    is_visible_to_live_users = models.BooleanField(default=False)
    is_visible_to_on_demand_users = models.BooleanField(default=True)
    is_visible_to_self_paced_users = models.BooleanField(default=True)
    is_visible_to_group_users = models.BooleanField(default=False)
    is_visible_to_cohort_users = models.BooleanField(default=False)
    is_visible_to_mentored_users = models.BooleanField(default=False)
    is_visible_to_project_based_users = models.BooleanField(default=False)
    is_visible_to_exclusive_users = models.BooleanField(default=False)
    is_visible_to_waitlist_users = models.BooleanField(default=False)
    is_visible_to_discounted_users = models.BooleanField(default=False)
    is_visible_to_certificate_users = models.BooleanField(default=False)
    is_visible_to_approved_users = models.BooleanField(default=False)
    is_visible_to_recommended_users = models.BooleanField(default=False)
    is_visible_to_archived_users = models.BooleanField(default=False)
    is_visible_to_featured_users = models.BooleanField(default=False)
    is_visible_to_public_users = models.BooleanField(default=True)
    is_visible_to_enrolled_users_only = models.BooleanField(default=False)
    is_visible_to_instructors_only = models.BooleanField(default=False)
    is_visible_to_admins_only = models.BooleanField(default=False)
    is_visible_to_guests_only = models.BooleanField(default=False)
    is_visible_to_waitlisted_users_only = models.BooleanField(default=False)
    is_visible_to_non_enrolled_users_only = models.BooleanField(default=False)
    is_visible_to_premium_users_only = models.BooleanField(default=False)
    is_visible_to_free_users_only = models.BooleanField(default=False)
    is_visible_to_live_users_only = models.BooleanField(default=False)
    is_visible_to_on_demand_users_only = models.BooleanField(default=False)
    is_visible_to_self_paced_users_only = models.BooleanField(default=False)
    is_visible_to_group_users_only = models.BooleanField(default=False)

    def __str__(self):
        return self.title